{{- if .Values.image_version_ironic_api }}
kind: Service
apiVersion: v1

metadata:
  name: ironic-api
  labels:
    system: openstack
    type: api
    component: ironic
spec:
  selector:
    name: ironic-api
  ports:
    - name: ironic-api
      port: {{.Values.global.ironic_api_port_internal}}
{{ end }}
